
post http://localhost:8080/api/users/register
Content-Type:application/json

{
"firstName":"Emmanuel kipmurkor",
 "middleName":"Kipmurkor", 
 "lastName":"emmanuel",
 "email":"emmanuelkipmurkor@gmail.com",
 "password": "kim8717166"
}


